import type { Project, Skill, Profile, Experience } from "@/types";

export const fallbackProfile: Profile = {
  id: 1,
  name: "Surya Eko Indrawan",
  role: "Full-stack Developer",
  location: "Semarang, Jawa Tengah, Indonesia",
  bio: "Pengembang berpengalaman dengan riwayat kerja yang kuat di industri hiburan. Memiliki keahlian teknis dalam Yii2, Python, Back-End Web Development, dan Ubuntu Server. Profesional di bidang teknik yang fokus pada solusi pengembangan yang solid.",
  avatar_url: null,
  open_to_work: true,
};

export const fallbackExperiences: Experience[] = [
  {
    id: 1,
    type: "work",
    company: "Visionic Indonesia",
    role: "Full-stack Developer",
    start_date: "2018-01-01",
    end_date: null,
    is_current: true,
    location: "Semarang, Jawa Tengah, Indonesia",
    description: "Laravel, Yii, Vue, React, Node.js, dan pengembangan aplikasi web terintegrasi.",
    sort_order: 1,
  },
  {
    id: 2,
    type: "work",
    company: "IKSA",
    role: "IT Specialist",
    start_date: "2018-02-01",
    end_date: "2022-01-01",
    is_current: false,
    location: "Semarang, Jawa Tengah, Indonesia",
    description: "",
    sort_order: 2,
  },
  {
    id: 3,
    type: "work",
    company: "HAHO",
    role: "IT Specialist",
    start_date: "2016-01-01",
    end_date: "2018-01-01",
    is_current: false,
    location: "",
    description: "",
    sort_order: 3,
  },
  {
    id: 4,
    type: "work",
    company: "Visionic Indonesia",
    role: "Developer",
    start_date: "2015-01-01",
    end_date: "2016-01-01",
    is_current: false,
    location: "Semarang, Jawa Tengah, Indonesia",
    description: "",
    sort_order: 4,
  },
  {
    id: 5,
    type: "education",
    company: "SMK N 11 Semarang",
    role: "Siswa",
    start_date: "2012-01-01",
    end_date: "2015-01-01",
    is_current: false,
    location: "Semarang",
    description: "Web developer, mobile developer, game developer, multimedia, dan pembuat film.",
    sort_order: 5,
  },
];

export const fallbackProjects: Project[] = [
  {
    id: 1,
    name: "BAKPK Polines",
    description: "Sistem Bagian Akademik, Kemahasiswaan, Perencanaan, dan Kerjasama (BAKPK). Fitur utama: integrasi master data Polines, implementasi pembayaran berbagai bank (Host-to-host & API), otomatisasi manajemen status mahasiswa berdasarkan pembayaran UKT.",
    start_date: "2021-11-01",
    end_date: "2022-04-01",
    url: "https://bakpk.polines.ac.id/",
    tech_stack: ["Laravel", "MySQL", "API"],
    featured: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: "Website Polines",
    description: "Desain, pengembangan, dan migrasi situs utama Politeknik Negeri Semarang.",
    start_date: "2021-09-01",
    end_date: "2021-11-01",
    url: "https://www.polines.ac.id/",
    tech_stack: ["PHP", "MySQL", "JavaScript"],
    featured: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: "Event Certification — Fikri Organizer",
    description: "Otomatisasi pembuatan sertifikat event, unggah ke Google Drive, dan pengiriman email ke peserta, panitia, pembicara, dan moderator.",
    start_date: "2022-04-01",
    end_date: "2022-04-01",
    url: null,
    tech_stack: ["Node.js", "Google Drive API", "Sendinblue API"],
    featured: true,
    sort_order: 3,
  },
  {
    id: 4,
    name: "Sistem Konseling Online Upgris",
    description: "Sistem konseling dan pelatihan untuk Universitas PGRI Semarang (Upgris).",
    start_date: "2021-08-01",
    end_date: "2021-11-01",
    url: "https://skao.upgris.ac.id/",
    tech_stack: ["PHP", "MySQL", "JavaScript"],
    featured: true,
    sort_order: 4,
  },
  {
    id: 5,
    name: "Warehousing & Accounting — PT Anzaerara",
    description: "Sistem pergudangan dan akuntansi perusahaan untuk PT Anzaerara Soeboer Group.",
    start_date: "2021-04-01",
    end_date: "2021-08-01",
    url: null,
    tech_stack: ["PHP", "MySQL"],
    featured: false,
    sort_order: 5,
  },
  {
    id: 6,
    name: "PSMS Indra Karya",
    description: "Sistem manajemen dan monitoring sanitasi.",
    start_date: "2021-09-01",
    end_date: "2021-10-01",
    url: "https://psms.indrakarya.co.id/",
    tech_stack: ["PHP", "MySQL"],
    featured: false,
    sort_order: 6,
  },
  {
    id: 7,
    name: "HAHO",
    description: "Aplikasi jejaring sosial hiburan untuk merekrut talenta, kolaborasi kreatif, dan info audisi/event.",
    start_date: "2016-06-01",
    end_date: "2018-04-01",
    url: "https://haho.co.id/",
    tech_stack: ["PHP", "MySQL", "Android"],
    featured: true,
    sort_order: 7,
  },
  {
    id: 8,
    name: "My Semarang Travel Guide",
    description: "Aplikasi mobile panduan wisata multi-bahasa untuk Kota Semarang.",
    start_date: "2018-12-01",
    end_date: "2019-01-01",
    url: null,
    tech_stack: ["Android", "Java"],
    featured: false,
    sort_order: 8,
  },
];

export const fallbackSkills: Skill[] = [
  { id: 1, name: "React", category: "frontend" },
  { id: 2, name: "Vue", category: "frontend" },
  { id: 3, name: "JavaScript", category: "frontend" },
  { id: 4, name: "TypeScript", category: "frontend" },
  { id: 5, name: "Laravel", category: "backend" },
  { id: 6, name: "PHP", category: "backend" },
  { id: 7, name: "Yii2", category: "backend" },
  { id: 8, name: "Node.js", category: "backend" },
  { id: 9, name: "Python", category: "backend" },
  { id: 10, name: "Ubuntu Server", category: "tools" },
  { id: 11, name: "Docker", category: "tools" },
  { id: 12, name: "GitHub", category: "tools" },
  { id: 13, name: "MySQL", category: "tools" },
  { id: 14, name: "Firebase", category: "tools" },
];
